Helmes_Reg/Controllers/Helmes_Entries_dbController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Helmes_Reg;

namespace Helmes_Reg.Controllers
{
    public class Helmes_Entries_dbController : Controller
    {
        private HelmesTestEntities db = new HelmesTestEntities();

        // GET: Helmes_Entries_db
        public ActionResult Index()
        {
            return View(db.Helmes_Entries_db.ToList());
        }

        // GET: Helmes_Entries_db/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Helmes_Entries_db helmes_Entries_db = db.Helmes_Entries_db.Find(id);
            if (helmes_Entries_db == null)
            {
                return HttpNotFound();
            }
            return View(helmes_Entries_db);
        }

        // GET: Helmes_Entries_db/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Helmes_Entries_db/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EntryID,FullName,Sectors,Agree")] Helmes_Entries_db helmes_Entries_db)
        {
            if (ModelState.IsValid)
            {
                db.Helmes_Entries_db.Add(helmes_Entries_db);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(helmes_Entries_db);
        }

      

        // GET: Helmes_Entries_db/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Helmes_Entries_db helmes_Entries_db = db.Helmes_Entries_db.Find(id);
            if (helmes_Entries_db == null)
            {
                return HttpNotFound();
            }
            return View(helmes_Entries_db);
        }

        // POST: Helmes_Entries_db/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EntryID,FullName,Sectors,Agree")] Helmes_Entries_db helmes_Entries_db)
        {
            if (ModelState.IsValid)
            {
                db.Entry(helmes_Entries_db).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(helmes_Entries_db);
        }

        // GET: Helmes_Entries_db/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Helmes_Entries_db helmes_Entries_db = db.Helmes_Entries_db.Find(id);
            if (helmes_Entries_db == null)
            {
                return HttpNotFound();
            }
            return View(helmes_Entries_db);
        }

        // POST: Helmes_Entries_db/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Helmes_Entries_db helmes_Entries_db = db.Helmes_Entries_db.Find(id);
            db.Helmes_Entries_db.Remove(helmes_Entries_db);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Helmes_Reg/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Helmes_Reg.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Helmes_Reg/Views/Helmes_Entries_db/Create.cshtml
@model Helmes_Reg.Helmes_Entries_db

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Helmes_Entries_db</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EntryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntryID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EntryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            @Html.LabelFor(model => model.Sectors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sectors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sectors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Agree, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Agree)
                    @Html.ValidationMessageFor(model => model.Agree, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Helmes_Reg/Views/Helmes_Entries_db/Create2.cshtml
@model Helmes_Reg.Helmes_Entries_db

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Helmes_Entries_db</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EntryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntryID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EntryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sectors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sectors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sectors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Agree, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Agree)
                    @Html.ValidationMessageFor(model => model.Agree, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Helmes_Reg/Views/Helmes_Entries_db/Delete.cshtml
@model Helmes_Reg.Helmes_Entries_db

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Helmes_Entries_db</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sectors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sectors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agree)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agree)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Helmes_Reg/Views/Helmes_Entries_db/Details.cshtml
@model Helmes_Reg.Helmes_Entries_db

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Helmes_Entries_db</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sectors)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sectors)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agree)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agree)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EntryID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Helmes_Reg/Views/Helmes_Entries_db/Edit.cshtml
@model Helmes_Reg.Helmes_Entries_db

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Helmes_Entries_db</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EntryID)

        <div class="form-group">
            @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sectors, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sectors, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sectors, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Agree, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Agree)
                    @Html.ValidationMessageFor(model => model.Agree, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Helmes_Reg/Views/Helmes_Entries_db/Index.cshtml
@model IEnumerable<Helmes_Reg.Helmes_Entries_db>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sectors)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Agree)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sectors)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Agree)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EntryID }) |
            @Html.ActionLink("Details", "Details", new { id=item.EntryID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EntryID })
        </td>
    </tr>
}

</table>

Helmes_Reg/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Helmes_Reg/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>You like? Yes?!?</h2>
<h3>Well, then call me!</h3>



<address>
    <strong>Email</strong>   <a href="mailto:Miltopgert@gmail.com">Miltopgert@gmail.com</a><br />
    <strong>Mobile</strong> 522 4646 aka 52 BINGO</a><br />
</address>

Helmes_Reg/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="jumbotron">
    <h1>Register</h1>

    <p>
        Please enter your name and pick the Sectors you are currently involved in.
    </p>
 
        <form action="" method="post">
        <p>
            <input required type="text" placeholder="Insert your name" name="Name" value="@Request.Form["Name"]">
        </p>
        <!--

        Seems that there are enough material on how to populate dropdown list with database fields, but at the moment they remain mysterious to me :)
        but I made all the fields mandatory and used optgroupes to reduce the use of non/breaking spaces.

        -->
        <p>
            <select required multiple size="7" name="Choices" value="@Request.Form["Choices"]">
                <optgroup label="Manufacturing">
                    <option value="19">Construction materials</option>
                    <option value="18">Electronics and Optics</option>
                    <option value="6">Food and Beverage</option>
                    <option value="342">&nbsp;&nbsp;&nbsp;&nbsp;Bakery &amp; confectionery products</option>
                    <option value="43">&nbsp;&nbsp;&nbsp;&nbsp;Beverages</option>
                    <option value="42">&nbsp;&nbsp;&nbsp;&nbsp;Fish &amp; fish products </option>
                    <option value="40">&nbsp;&nbsp;&nbsp;&nbsp;Meat &amp; meat products</option>
                    <option value="39">&nbsp;&nbsp;&nbsp;&nbsp;Milk &amp; dairy products </option>
                    <option value="437">&nbsp;&nbsp;&nbsp;&nbsp;Other</option>
                    <option value="378">&nbsp;&nbsp;&nbsp;&nbsp;Sweets &amp; snack food</option>
                    <option value="13">Furniture</option>
                    <option value="389">&nbsp;&nbsp;&nbsp;&nbsp;Bathroom/sauna </option>
                    <option value="385">&nbsp;&nbsp;&nbsp;&nbsp;Bedroom</option>
                    <option value="390">&nbsp;&nbsp;&nbsp;&nbsp;Children’s room </option>
                    <option value="98">&nbsp;&nbsp;&nbsp;&nbsp;Kitchen </option>
                    <option value="101">&nbsp;&nbsp;&nbsp;&nbsp;Living room </option>
                    <option value="392">&nbsp;&nbsp;&nbsp;&nbsp;Office</option>
                    <option value="394">&nbsp;&nbsp;&nbsp;&nbsp;Other (Furniture)</option>
                    <option value="341">&nbsp;&nbsp;&nbsp;&nbsp;Outdoor </option>
                    <option value="99">&nbsp;&nbsp;&nbsp;&nbsp;Project furniture</option>
                    <option value="12">Machinery</option>
                    <option value="94">&nbsp;&nbsp;&nbsp;&nbsp;Machinery components</option>
                    <option value="91">&nbsp;&nbsp;&nbsp;&nbsp;Machinery equipment/tools</option>
                    <option value="224">&nbsp;&nbsp;&nbsp;&nbsp;Manufacture of machinery </option>
                    <option value="97">&nbsp;&nbsp;&nbsp;&nbsp;Maritime</option>
                    <option value="271">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Aluminium and steel workboats </option>
                    <option value="269">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Boat/Yacht building</option>
                    <option value="230">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ship repair and conversion</option>
                    <option value="93">&nbsp;&nbsp;&nbsp;&nbsp;Metal structures</option>
                    <option value="508">&nbsp;&nbsp;&nbsp;&nbsp;Other</option>
                    <option value="227">&nbsp;&nbsp;&nbsp;&nbsp;Repair and maintenance service</option>
                    <option value="11">Metalworking</option>
                    <option value="67">&nbsp;&nbsp;&nbsp;&nbsp;Construction of metal structures</option>
                    <option value="263">&nbsp;&nbsp;&nbsp;&nbsp;Houses and buildings</option>
                    <option value="267">&nbsp;&nbsp;&nbsp;&nbsp;Metal products</option>
                    <option value="542">&nbsp;&nbsp;&nbsp;&nbsp;Metal works</option>
                    <option value="75">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;CNC-machining</option>
                    <option value="62">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Forgings, Fasteners </option>
                    <option value="69">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Gas, Plasma, Laser cutting</option>
                    <option value="66">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;MIG, TIG, Aluminum welding</option>
                    <option value="9">Plastic and Rubber</option>
                    <option value="54">&nbsp;&nbsp;&nbsp;&nbsp;Packaging</option>
                    <option value="556">&nbsp;&nbsp;&nbsp;&nbsp;Plastic goods</option>
                    <option value="559">&nbsp;&nbsp;&nbsp;&nbsp;Plastic processing technology</option>
                    <option value="55">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Blowing</option>
                    <option value="57">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Moulding</option>
                    <option value="53">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Plastics welding and processing</option>
                    <option value="560">&nbsp;&nbsp;&nbsp;&nbsp;Plastic profiles</option>
                    <option value="5">Printing </option>
                    <option value="148">&nbsp;&nbsp;&nbsp;&nbsp;Advertising</option>
                    <option value="150">&nbsp;&nbsp;&nbsp;&nbsp;Book/Periodicals printing</option>
                    <option value="145">&nbsp;&nbsp;&nbsp;&nbsp;Labelling and packaging printing</option>
                    <option value="7">Textile and Clothing</option>
                    <option value="44">&nbsp;&nbsp;&nbsp;&nbsp;Clothing</option>
                    <option value="45">&nbsp;&nbsp;&nbsp;&nbsp;Textile</option>
                    <option value="8">Wood</option>
                    <option value="337">&nbsp;&nbsp;&nbsp;&nbsp;Other (Wood)</option>
                    <option value="51">&nbsp;&nbsp;&nbsp;&nbsp;Wooden building materials</option>
                    <option value="47">&nbsp;&nbsp;&nbsp;&nbsp;Wooden houses</option>
                </optgroup>
                <optgroup label="Other">
                    <option value="37">&nbsp;&nbsp;&nbsp;&nbsp;Creative industries</option>
                    <option value="29">&nbsp;&nbsp;&nbsp;&nbsp;Energy technology</option>
                    <option value="33">&nbsp;&nbsp;&nbsp;&nbsp;Environment</option>
                </optgroup>
                <optgroup label="Services">
                    <option value="25">Business services</option>
                    <option value="35">Engineering</option>
                    <option value="28">Information Technology and Telecommunications</option>
                    <option value="581">&nbsp;&nbsp;&nbsp;&nbsp;Data processing, Web portals, E-marketing</option>
                    <option value="576">&nbsp;&nbsp;&nbsp;&nbsp;Programming, Consultancy</option>
                    <option value="121">&nbsp;&nbsp;&nbsp;&nbsp;Software, Hardware</option>
                    <option value="122">&nbsp;&nbsp;&nbsp;&nbsp;Telecommunications</option>
                    <option value="22">Tourism</option>
                    <option value="141">Translation services</option>
                    <option value="21">Transport and Logistics</option>
                    <option value="111">&nbsp;&nbsp;&nbsp;&nbsp;Air</option>
                    <option value="114">&nbsp;&nbsp;&nbsp;&nbsp;Rail</option>
                    <option value="112">&nbsp;&nbsp;&nbsp;&nbsp;Road</option>
                    <option value="113">&nbsp;&nbsp;&nbsp;&nbsp;Water</option>
                </optgroup>
            </select>
        </p>
        <p>
            <input required type="checkbox" default="false" name="Terms" value="@Request.Form["Terms"]"> Agree to terms
        </p>
        <p>
          <input type="submit" value="Save" name="upload">
        </p>
        </form>


</div>

Helmes_Reg/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Helmes Registration App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Helmes Registration", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Entries", "Index", "Helmes_Entries_db")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Miltop's Helmes Registration App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>